-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 10:38:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exercises` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exercises` (
  `idExercises` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`idExercises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`questions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `type` INT NOT NULL,
  `FK_idExercises` INT NOT NULL,
  PRIMARY KEY (`idQuestions`),
  INDEX `fk_Questions_Exercises1_idx` (`FK_idExercises` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Exercises1`
    FOREIGN KEY (`FK_idExercises`)
    REFERENCES `mydb`.`exercises` (`idExercises`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fullfilments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fullfilments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fullfilments` (
  `idFullfilment` INT NOT NULL AUTO_INCREMENT,
  `FK_idExercises` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  INDEX `fk_Exercises_has_Responses_Exercises1_idx` (`FK_idExercises` ASC) VISIBLE,
  PRIMARY KEY (`idFullfilment`),
  UNIQUE INDEX `idFullfilment_UNIQUE` (`idFullfilment` ASC) VISIBLE,
  CONSTRAINT `fk_Exercises_has_Responses_Exercises1`
    FOREIGN KEY (`FK_idExercises`)
    REFERENCES `mydb`.`exercises` (`idExercises`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`responses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`responses` (
  `idResponses` INT NOT NULL AUTO_INCREMENT,
  `FK_idQuestions` INT NOT NULL,
  `content` VARCHAR(100) NULL,
  `fullfilments_idFullfilment` VARCHAR(45) NOT NULL,
  INDEX `fk_Questions_has_User_Questions_idx` (`FK_idQuestions` ASC) VISIBLE,
  PRIMARY KEY (`idResponses`),
  INDEX `fk_responses_fullfilments1_idx` (`fullfilments_idFullfilment` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_has_User_Questions`
    FOREIGN KEY (`FK_idQuestions`)
    REFERENCES `mydb`.`questions` (`idQuestions`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responses_fullfilments1`
    FOREIGN KEY (`fullfilments_idFullfilment`)
    REFERENCES `mydb`.`fullfilments` (`idFullfilment`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
